name: 'CI'

on:
  pull_request:

jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm ci

  test:
    needs: build
    name: 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: npm run test-ci
