name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Release Branch
        run: |
          git checkout -b release/${{ github.ref_name }} ${{ github.ref_name }}
          git push origin release/${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Generate Changelog
        id: changelog
        run: |
          PREV_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          CHANGELOG=$(git log --pretty=format:"- %s" $PREV_TAG..HEAD)
          echo "CHANGELOG=$CHANGELOG" >> $GITHUB_ENV

      - name: Create Release Issue
        run: node .github/actions/create-release-issue.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          CHANGELOG: ${{ env.CHANGELOG }}

      - name: Run tests
        run: npm run test-ci
