name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Release Branch
        run: |
          git checkout -b release/${{ github.ref_name }}
          git push origin release/${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm run test-ci

      - name: Build
        run: npm run build

      - name: Create Release Issue
        run: node .github/actions/create-release-issue.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          github_actor: ${{ github.actor }}
          github_ref_name: ${{ github.ref_name }}
