name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if Release Branch exists
        id: check_branch
        run: |
          if git show-ref --quiet refs/remotes/origin/release/${{ github.ref_name }}
          then
            echo "BRANCH_EXISTS=true" >> $GITHUB_ENV
          fi

      - name: Switch to existing Release Branch or Create new
        run: |
          if [ "${{ env.BRANCH_EXISTS }}" = "true" ]
          then
            git checkout release/${{ github.ref_name }}
          else
            git checkout -b release/${{ github.ref_name }} ${{ github.ref_name }}
            git push origin release/${{ github.ref_name }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Generate Changelog
        id: changelog
        run: |
          PREV_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          LAST_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --max-count=1`)
          CHANGELOG=$(git log --pretty="- %s" $PREV_TAG..$LAST_TAG | tr '\n' ';')
          echo "CHANGELOG=$CHANGELOG" >> $GITHUB_ENV

      - name: Create Release Issue
        run: node .github/actions/create-release-issue.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          CHANGELOG: ${{ env.CHANGELOG }}

      - name: Run tests
        id: tests
        run: npm run test-ci || echo "TEST_FAILED=true" >> $GITHUB_ENV
        continue-on-error: true

      - name: Update Issue after tests
        run: node .github/actions/update-release-issue.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          TEST_RESULT: ${{ env.TEST_FAILED }}
